server:
  port: 9000

spring:
  application:
    name: netty-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:18800/eureka/
    registry-fetch-interval-seconds: 50